title: Muchammad Abdur Rochman
description: 'Pelajar Yang Tak Pernah Pintar'
url: ''
paginate: 5
permalink: pretty
cover_image: /bg.jpeg
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec
twitter:
  username: rahman_shalehh
  card: summary
logo: logo.png
social:
  name: Rahman.Shalehh
  links:
    - 'https://twitter.com/rahman_shalehh'
    - 'https://github.com/Rahman-Shalehh'
    - 'https://www.instagram.com/rahman.shalehh'
google_site_verification: xxxxx
lang: en
sass:
  sass_dir: _sass
  style: ':compressed'
author:
  name: Rahman Shalehh
  url: 'https://github.com/Rahman-Shalehh'
  email: muchammad1101@gmail.com
baseurl: ''
